name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  ENV: test
jobs:
  - job: One
    steps:
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
  - job: Maven
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          codeCoverageToolOption: JaCoCo
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          goals: 'clean install'