name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  ENV: test
jobs:
  - job: Maven
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          codeCoverageToolOption: JaCoCo
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          goals: 'clean install'